/*
 * src/c/mdbl.c
 * Default Alloy entry point — do not modify.
 * Generated by: pebble new-project --alloy
 */
 
#include <pebble.h>
 
int main(void) {
    Window *w = window_create();
    window_stack_push(w, true);
    moddable_createMachine(NULL);
    window_destroy(w);
}
 